const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const fmt=n=>Number(n||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'});
const uid=()=>crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36);
const store={get(){return JSON.parse(localStorage.getItem('gastosPro')||'{"expenses":[],"cards":["BBVA","Banamex","Nu","Apple Card"],"apiUrl":""}')},set(d){localStorage.setItem('gastosPro',JSON.stringify(d));render();}};
let calDate=new Date(); let deferredPrompt=null; let calc='0';
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});
$('#installBtn').onclick=()=>deferredPrompt?.prompt();
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');
function init(){ $('#todayLabel').textContent=new Date().toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long'}); bind(); render(); }
function bind(){
 $$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');});
 $('#expenseForm').onsubmit=e=>{e.preventDefault();const d=store.get();d.expenses.push({id:uid(),concept:$('#concept').value,amount:+$('#amount').value,paid:+$('#paid').value||0,card:$('#cardName').value,dueDate:$('#dueDate').value,category:$('#category').value,notes:$('#notes').value,createdAt:new Date().toISOString(),status:(+$('#paid').value>=+$('#amount').value?'paid':'pending')});store.set(d);e.target.reset();$('#paid').value=0;};
 $('#cardForm').onsubmit=e=>{e.preventDefault();const v=$('#newCard').value.trim();if(!v)return;const d=store.get();d.cards.push(v);store.set(d);e.target.reset();};
 $('#clearBtn').onclick=()=>confirm('¿Borrar todos los gastos?')&&(store.set({...store.get(),expenses:[]}));
 $('#demoBtn').onclick=()=>{const d=store.get();d.expenses.push({id:uid(),concept:'Cancún',amount:7400,paid:2000,card:'BBVA',dueDate:new Date(Date.now()+864e5*7).toISOString().slice(0,10),category:'Viaje',notes:'Restan 5400',createdAt:new Date().toISOString(),status:'pending'});store.set(d)};
 $('#exportBtn').onclick=()=>downloadJSON(); $('#importInput').onchange=importJSON; $('#saveApi').onclick=()=>{const d=store.get();d.apiUrl=$('#apiUrl').value;store.set(d)};
 $('#prevMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar(store.get())}; $('#nextMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar(store.get())};
 ['7','8','9','÷','4','5','6','×','1','2','3','-','0','.','=','+','C'].forEach(k=>{const b=document.createElement('button');b.textContent=k;b.onclick=()=>calcKey(k);$('#calcKeys').appendChild(b)});
}
function render(){const d=store.get(), now=new Date(); $('#monthName').textContent=now.toLocaleDateString('es-MX',{month:'long'}); fillCards(d); renderTotals(d); renderLists(d); renderCalendar(d); $('#jsonPreview').value=JSON.stringify(d,null,2); $('#apiUrl').value=d.apiUrl||'';}
function fillCards(d){$('#cardName').innerHTML=d.cards.map(c=>`<option>${c}</option>`).join('');$('#cardsList').innerHTML=d.cards.map(c=>`<span class="chip">${c}</span>`).join('');}
function renderTotals(d){const month=new Date().getMonth(), year=new Date().getFullYear();const m=d.expenses.filter(x=>{const dt=new Date(x.dueDate+'T00:00');return dt.getMonth()==month&&dt.getFullYear()==year});const total=m.reduce((s,x)=>s+x.amount,0), paid=m.reduce((s,x)=>s+(x.status==='paid'?x.amount:x.paid),0), pending=Math.max(0,total-paid);$('#balanceAmount').textContent=fmt(total);$('#paidAmount').textContent=fmt(paid);$('#pendingAmount').textContent=fmt(pending);$('#cardsCount').textContent=d.cards.length;}
function renderLists(d){const sorted=[...d.expenses].sort((a,b)=>a.dueDate.localeCompare(b.dueDate));const upcoming=sorted.filter(x=>x.status!=='paid').slice(0,6);$('#upcomingList').innerHTML=upcoming.map(itemHTML).join('')||'<p class="muted">Sin pagos pendientes.</p>';$('#expenseList').innerHTML=sorted.map(itemHTML).join('')||'<p class="muted">Aún no hay movimientos.</p>';$('#nextPaymentCard').innerHTML=upcoming[0]?`<h3>Siguiente pago</h3><p>${upcoming[0].concept} vence el ${dateMx(upcoming[0].dueDate)}</p><h2>${fmt(upcoming[0].amount-upcoming[0].paid)}</h2>`:'<h3>Todo limpio ✨</h3><p>No tienes pagos próximos registrados.</p>';$$('.amount-box button').forEach(b=>b.onclick=()=>markPaid(b.dataset.id));}
function itemHTML(x){const rest=Math.max(0,x.amount-x.paid);return `<article class="expense-item"><div><h4>${x.concept}</h4><p>${x.card} · ${x.category}</p><small>${dateMx(x.dueDate)} ${x.notes?'· '+x.notes:''}</small></div><div class="amount-box"><strong>${fmt(x.amount)}</strong><span>${x.status==='paid'?'Pagado':'Restan '+fmt(rest)}</span><button data-id="${x.id}">✓</button></div></article>`;}
function markPaid(id){const d=store.get();const x=d.expenses.find(e=>e.id===id); if(x){x.paid=x.amount;x.status='paid';store.set(d)}}
function renderCalendar(d){const y=calDate.getFullYear(),m=calDate.getMonth();$('#calendarTitle').textContent=calDate.toLocaleDateString('es-MX',{month:'long',year:'numeric'});const first=(new Date(y,m,1).getDay()+6)%7, days=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<first;i++)html+='<div></div>';for(let day=1;day<=days;day++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const has=d.expenses.some(x=>x.dueDate===iso);const today=iso===new Date().toISOString().slice(0,10);html+=`<div class="day ${has?'has':''} ${today?'today':''}">${day}${has?'<div class="dot"></div>':''}</div>`}$('#calendarGrid').innerHTML=html;}
function dateMx(v){return new Date(v+'T00:00').toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'});} 
function downloadJSON(){const blob=new Blob([JSON.stringify(store.get(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='respaldo-mis-gastos.json';a.click();}
function importJSON(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data.expenses||!data.cards)throw Error();store.set(data)}catch{alert('JSON no válido')}};r.readAsText(f);}
function calcKey(k){if(k==='C')calc='0';else if(k==='='){try{calc=String(Function('return '+calc.replaceAll('×','*').replaceAll('÷','/'))())}catch{calc='Error'}}else calc=calc==='0'?k:calc+k;$('#calcDisplay').value=calc;}
init();
